#!/bin/bash
# Quick Start - InsurSmart
# Usage: ./start.sh

echo "🚀 InsurSmart - Quick Start"
echo "============================"
echo ""
echo "✅ Instructions de lancement:"
echo ""
echo "OPTION 1: Lancer les 3 terminaux (Recommandé)"
echo ""
echo "Terminal 1 - Backend:"
echo "  cd backend && npm start"
echo ""
echo "Terminal 2 - Web:"
echo "  cd web && npm start"
echo ""
echo "Terminal 3 - Mobile:"
echo "  cd mobile && npm start"
echo ""
echo "OPTION 2: Lancer avec npm-run-all (single command)"
echo ""
echo "  npm install -g npm-run-all"
echo "  npm-run-all --parallel \"cd backend && npm start\" \"cd web && npm start\" \"cd mobile && npm start\""
echo ""
echo "✅ Accès:"
echo "  - Backend API: http://localhost:5000"
echo "  - Web App: http://localhost:3000"
echo "  - Mobile App: http://localhost:3001"
echo ""
echo "🧪 Tester l'API:"
echo "  curl http://localhost:5000/api/health"
echo ""
